### ISSUE TITLE
Exception:exception 'RenanBr\BibTexParser\Exception\ParserException' with message 'Unexpected character 'q' at line 11 column 1476'

### ISSUE THREAD

**Issue by M4Lien** [renanbr/bibtex-parser#57] opened 2018-12-22 02:41 UTC
https://www.sciencedirect.com/science/article/pii/S0022460X15007506
The following is Bibtex file content.
@article{ABBOUD2016305,
title = "Deterministic-random separation in nonstationary regime",
journal = "Journal of Sound and Vibration",
volume = "362",
pages = "305 - 326",
year = "2016",
issn = "0022-460X",
doi = "https://doi.org/10.1016/j.jsv.2015.09.029",
url = "http://www.sciencedirect.com/science/article/pii/S0022460X15007506",
author = "D. Abboud and J. Antoni and S. Sieg-Zieba and M. Eltabach",
abstract = "In rotating machinery vibration analysis, the synchronous average is perhaps the most widely used technique for extracting periodic components. Periodic components are typically related to gear vibrations, misalignments, unbalances, blade rotations, reciprocating forces, etc. Their separation from other random components is essential in vibration-based diagnosis in order to discriminate useful information from masking noise. However, synchronous averaging theoretically requires the machine to operate under stationary regime (i.e. the related vibration signals are cyclostationary) and is otherwise jeopardized by the presence of amplitude and phase modulations. A first object of this paper is to investigate the nature of the nonstationarity induced by the response of a linear time-invariant system subjected to speed varying excitation. For this purpose, the concept of a cyclo-non-stationary signal is introduced, which extends the class of cyclostationary signals to speed-varying regimes. Next, a “generalized synchronous average’’ is designed to extract the deterministic part of a cyclo-non-stationary vibration signal—i.e. the analog of the periodic part of a cyclostationary signal. Two estimators of the GSA have been proposed. The first one returns the synchronous average of the signal at predefined discrete operating speeds. A brief statistical study of it is performed, aiming to provide the user with confidence intervals that reflect the "quality" of the estimator according to the SNR and the estimated speed. The second estimator returns a smoothed version of the former by enforcing continuity over the speed axis. It helps to reconstruct the deterministic component by tracking a specific trajectory dictated by the speed profile (assumed to be known a priori).The proposed method is validated first on synthetic signals and then on actual industrial signals. The usefulness of the approach is demonstrated on envelope-based diagnosis of bearings in variable-speed operation."
}
I am trying to parse this file using your lib, but it don't work.
I've got this error:
Exception:exception 'RenanBr\BibTexParser\Exception\ParserException' with message 'Unexpected character 'q' at line 11 column 1476' in ....
How I can solve this issue?
(I think it is a quote process like "quality".)

**Comment by renanbr** [comment] 2018-12-27 06:58
Thanks for reporting this.
I can reproduce the error you mentioned.
By the way, quotes should be escaped when it's inside a quoted text.

> As well as these accents, some characters can not be put directly into a BibTeX-entry, as they would conflict with the format description, like {, " or $. They need to be escaped using a backslash (\\).
>
> http://www.bibtex.org/SpecialSymbols/

See a valid entry (replacing `"quality"` with `\"quality\"`):
```
@article{ABBOUD2016305,
    title = "Deterministic-random separation in nonstationary regime",
    journal = "Journal of Sound and Vibration",
    volume = "362",
    pages = "305 - 326",
    year = "2016",
    issn = "0022-460X",
    doi = "https://doi.org/10.1016/j.jsv.2015.09.029",
    url = "http://www.sciencedirect.com/science/article/pii/S0022460X15007506",
    author = "D. Abboud and J. Antoni and S. Sieg-Zieba and M. Eltabach",
    abstract = "[...] that reflect the \"quality\" of the estimator [...]"
}
```

I think it's a bug from the ScienceDirect side.
Could you open an issue addressed to ScienceDirect team? (I didn't find any issue board)
Feel free to cite this issue.

**Comment by renanbr** [comment] 2019-01-30 09:09
closing as duplicate of #48

**Closed by renanbr** 2019-01-30 09:09 UTC
Labels: duplicate
